server:
  port: 8090

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.chinaentropy.model.domain
  mapperLocations: classpath:com.chinaentropy.model.mapper/*.xml


#默认使用配置
spring:
  profiles:
    active: test